jsonpCallback({"products":[
	{"id":1,"name":"Clams (6)","price":"3.50","itemType":"food"},
	{"id":2,"name":"Crab Cake","price":"6.00","itemType":"food"},
	{"id":3,"name":"Fried Calamari","price":"5.50","itemType":"food"},
	{"id":4,"name":"Fried Pickles","price":"4.50","itemType":"food"},
	{"id":5,"name":"Fries","price":"3.00","itemType":"food"},
	{"id":6,"name":"Chili Dog","price":"2.50","itemType":"food"},
	{"id":7,"name":"Kraut Dog","price":"2.00","itemType":"food"},
	{"id":8,"name":"Moz Sticks","price":"4.00","itemType":"food"},
	{"id":9,"name":"Onion Rings","price":"3.50","itemType":"food"},
	{"id":10,"name":"Poppers","price":"4.00","itemType":"food"},
	{"id":11,"name":"Wings","price":"9.00","itemType":"food"},
	{"id":12,"name":"Guinness Draft","price":"5.00","itemType":"draft"},
	{"id":13,"name":"Miller Lite Draft","price":"4.00","itemType":"draft"},
	{"id":14,"name":"Yuengling Draft","price":"4.00","itemType":"draft"},
	{"id":15,"name":"Blue Moon","price":"4.00","itemType":"bottle"},
	{"id":16,"name":"Corona","price":"4.00","itemType":"bottle"},
	{"id":17,"name":"Shandy","price":"4.00","itemType":"bottle"},
	{"id":18,"name":"Wine","price":"4.00","itemType":"bottle"},
	{"id":19,"name":"Coors NA","price":"2.50","itemType":"na"},
	{"id":20,"name":"Root Beer","price":"1.50","itemType":"na"},
	{"id":21,"name":"Water","price":"1.50","itemType":"na"},
	{"id":22,"name":"Ice","price":"7.00","itemType":"util"}
	],
    "sitename":"Pete and Larry's Place",
    "eventname":"St. Charles Carnival",
    "website":"www.scbcarnival.com",
    "logo":"logo.png"
    });

